const authorities=[
    {
        id: 0,
        position:"Secretary",
        content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate v.... Read More",
        image: "https://images.unsplash.com/photo-1672201050789-0b5454271405?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8cHJvZmlsZSUyMGluZGlhbnxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=400&q=60",
        ranking: "⭐️⭐️⭐️ ",
        name:"Narayan Naidu",
        contact: "9876543210",
    },
    {
        id: 1,
        position:"Treasurer",
        content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate v.... Read More",
        image: "https://images.unsplash.com/photo-1634843824921-83bb75483c59?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDd8fHByb2ZpbGUlMjBpbmRpYW58ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=400&q=60",
        ranking: "⭐️⭐️⭐️⭐️ ",
        name:"Damodar Yele",
        contact: "9876543210",
    },
    {
        id: 2,
        position:"Cultural head",
        content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate v.... Read More",
        image: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MzJ8fHByb2ZpbGUlMjBpbmRpYW58ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=400&q=60",
        ranking: "⭐️⭐️⭐️ ",
        name:"Sanjay Oberoi",
        contact: "9876541078",
    },
    {
        id: 3,
        position:"Security head",
        content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate v.... Read More",
        image: "https://images.unsplash.com/photo-1616002851413-ebcc9611139d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDB8fHByb2ZpbGUlMjBpbmRpYW4lMjByYWpwdXR8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=400&q=60",
        ranking: "⭐️⭐️⭐️⭐️ ",
        name:"Suraj Pratap Singh",
        contact: "8439876543",
    },
    {
        id: 4,
        position:"Technical head",
        content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate v.... Read More",
        image: "https://images.unsplash.com/photo-1583243553028-e4001cb6dd77?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NjR8fHByb2ZpbGUlMjBpbmRpYW4lMjByYWpwdXR8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=400&q=60",
        ranking: "⭐️⭐️⭐️⭐️⭐️",
        name:"Madhavi Bhawsar",
        contact: "9876543210",
    },
];
export  default authorities;