const event_doc=[
    {
        id: 0,
        title: "the event",
        image:  "https://images.unsplash.com/photo-1682252913872-2ec60d4b0818?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=876&q=80"  ,
        date: "10/3/2003",
        comment:"sdgvedrgverdgvswe dv dvc dsv sdvc sdv sdxvc vdsvdsv edvc x",
        category: "commity",
        important: true,        
    },
    {
        id: 12,
        title: "the event",
        image:  "https://images.unsplash.com/photo-1682252913872-2ec60d4b0818?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=876&q=80"  ,
        date: "10/3/2003",
        comment:"sdgvedrgverdgvswe dv dvc dsv sdvc sdv sdxvc vdsvdsv edvc x",
        category: "commity",
        important: true,        
    },
    {
        id: 13,
        title: "the event",
        image:  "https://images.unsplash.com/photo-1682252913872-2ec60d4b0818?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=876&q=80"  ,
        date: "10/3/2003",
        comment:"sdgvedrgverdgvswe dv dvc dsv sdvc sdv sdxvc vdsvdsv edvc x",
        category: "commity",
        important: true,        
    },
    {
        id: 14,
        title: "the event",
        image:  "https://images.unsplash.com/photo-1682252913872-2ec60d4b0818?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=876&q=80"  ,
        date: "10/3/2003",
        comment:"sdgvedrgverdgvswe dv dvc dsv sdvc sdv sdxvc vdsvdsv edvc x",
        category: "commity",
        important: true,        
    },
    {
        id: 1,
        title: "the edfdsvent",
        image:  "https://media.geeksforgeeks.org/img-practice/banner/cp-maths-java-thumbnail.png" ,
        date: "10/3/2003",
        comment:"sdgvedrgverdgvswe dv dvc dsv sdvc sdv sdxvc vdsvdsv edvc x",
        category: "society",
        important: false, 
    },
    {
        id: 2,
        title: "the evengsgst",
        image:  "https://images.unsplash.com/photo-1682252913872-2ec60d4b0818?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=876&q=80"  ,
        date: "10/3/2003",
        comment:"sdgvedrgverdgvswe dv dvc dsv sdvc sdv sdxvc vdsvdsv edvc x",
        category: "gym",
        important: false, 
    },
    {
        id: 3,
        title: "the evedsfdnt",
        image:  "https://media.geeksforgeeks.org/img-practice/banner/cp-maths-java-thumbnail.png"  ,
        date: "10/3/2003",
        comment:"sdgvedrgverdgvswe dv dvc dsv sdvc sdv sdxvc vdsvdsv edvc x",
        category: "society",
        important: true, 
    },
    {
        id: 15,
        title: "the evedsfdnt",
        image:  "https://media.geeksforgeeks.org/img-practice/banner/cp-maths-java-thumbnail.png"  ,
        date: "10/3/2003",
        comment:"sdgvedrgverdgvswe dv dvc dsv sdvc sdv sdxvc vdsvdsv edvc x",
        category: "society",
        important: true, 
    },
    {
        id: 16,
        title: "the evedsfdnt",
        image:  "https://media.geeksforgeeks.org/img-practice/banner/cp-maths-java-thumbnail.png"  ,
        date: "10/3/2003",
        comment:"sdgvedrgverdgvswe dv dvc dsv sdvc sdv sdxvc vdsvdsv edvc x",
        category: "society",
        important: true, 
    },
    {
        id: 17,
        title: "the evedsfdnt",
        image:  "https://media.geeksforgeeks.org/img-practice/banner/cp-maths-java-thumbnail.png"  ,
        date: "10/3/2003",
        comment:"sdgvedrgverdgvswe dv dvc dsv sdvc sdv sdxvc vdsvdsv edvc x",
        category: "society",
        important: true, 
    },
    {
        id: 4,
        title: "the esfzdvent",
        image:  "https://media.geeksforgeeks.org/img-practice/banner/cp-maths-java-thumbnail.png"  ,
        date: "10/3/2003",
        comment:"sdgvedrgverdgvswe dv dvc dsv sdvc sdv sdxvc vdsvdsv edvc x",
        category: "cultural",
        important: false, 
    },
    {
        id: 18,
        title: "the esfzdvent",
        image:  "https://media.geeksforgeeks.org/img-practice/banner/cp-maths-java-thumbnail.png"  ,
        date: "10/3/2003",
        comment:"sdgvedrgverdgvswe dv dvc dsv sdvc sdv sdxvc vdsvdsv edvc x",
        category: "cultural",
        important: false, 
    },
    {
        id: 19,
        title: "the esfzdvent",
        image:  "https://media.geeksforgeeks.org/img-practice/banner/cp-maths-java-thumbnail.png"  ,
        date: "10/3/2003",
        comment:"sdgvedrgverdgvswe dv dvc dsv sdvc sdv sdxvc vdsvdsv edvc x",
        category: "cultural",
        important: false, 
    },
    {
        id: 20,
        title: "the esfzdvent",
        image:  "https://media.geeksforgeeks.org/img-practice/banner/cp-maths-java-thumbnail.png"  ,
        date: "10/3/2003",
        comment:"sdgvedrgverdgvswe dv dvc dsv sdvc sdv sdxvc vdsvdsv edvc x",
        category: "cultural",
        important: false, 
    },
    {
        id: 5,
        title: "the dsfevent",
        image:  "https://images.unsplash.com/photo-1682252913872-2ec60d4b0818?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=876&q=80"  ,
        date: "10/3/2003",
        comment:"sdgvedrgverdgvswe dv dvc dsv sdvc sdv sdxvc vdsvdsv edvc x",
        category: "commity",
        important: true, 
    },
    {
        id: 6,
        title: "the event",
        image:  "https://media.geeksforgeeks.org/img-practice/banner/diving-into-excel-thumbnail.png"  ,
        date: "10/3/2003",
        comment:"sdgvedrgverdgvswe dv dvc dsv sdvc sdv sdxvc vdsvdsv edvc x",
        category: "commity",
        important: false, 
    },
    {
        id: 7,
        title: "the edfdsvent",
        image:  "https://images.unsplash.com/photo-1682252913872-2ec60d4b0818?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=876&q=80"  ,
        date: "10/3/2003",
        comment:"sdgvedrgverdgvswe dv dvc dsv sdvc sdv sdxvc vdsvdsv edvc x",
        category: "society",
        important: true, 
    },
    {
        id: 8,
        title: "the evengsgst",
        image:  "https://images.unsplash.com/photo-1682252913872-2ec60d4b0818?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=876&q=80"  ,
        date: "10/3/2003",
        comment:"sdgvedrgverdgvswe dv dvc dsv sdvc sdv sdxvc vdsvdsv edvc x",
        category: "gym",
        important: false, 
    },
    {
        id: 9,
        title: "the evedsfdnt",
        image:  "https://media.geeksforgeeks.org/img-practice/banner/cp-maths-java-thumbnail.png"  ,
        date: "10/3/2003",
        comment:"sdgvedrgverdgvswe dv dvc dsv sdvc sdv sdxvc vdsvdsv edvc x",
        category: "society",
        important: true, 
    },
    {
        id: 10,
        title: "the esfzdvent",
        image:  "https://media.geeksforgeeks.org/img-practice/banner/diving-into-excel-thumbnail.png"  ,
        date: "10/3/2003",
        comment:"sdgvedrgverdgvswe dv dvc dsv sdvc sdv sdxvc vdsvdsv edvc x",
        category: "cultural",
        important: true, 
    },
    {
        id: 21,
        title: "the esfzdvent",
        image:  "https://media.geeksforgeeks.org/img-practice/banner/diving-into-excel-thumbnail.png"  ,
        date: "10/3/2003",
        comment:"sdgvedrgverdgvswe dv dvc dsv sdvc sdv sdxvc vdsvdsv edvc x",
        category: "cultural",
        important: true, 
    },
    {
        id: 11,
        title: "the dsfevent",
        image:  "https://media.geeksforgeeks.org/img-practice/banner/cp-maths-java-thumbnail.png"  ,
        date: "10/3/2003",
        comment:"sdgvedrgverdgvswe dv dvc dsv sdvc sdv sdxvc vdsvdsv edvc x",
        category: "commity",
        important: false, 
    }
];
export default event_doc;