const event_doc=[
    {
        id: 0,
        title: "the event",
        image:  "https://images.unsplash.com/photo-1682252913872-2ec60d4b0818?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=876&q=80"  ,
        date: "10/3/2003",
        comment:"sdgvedrgverdgvswe dv dvc dsv sdvc sdv sdxvc vdsvdsv edvc x",
        category: "commity",
        organizer: "Secretory",
        important: true,  
        content:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",      
    },
    {
        id: 12,
        title: "the event",
        image:  "https://images.unsplash.com/photo-1682252913872-2ec60d4b0818?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=876&q=80"  ,
        date: "10/3/2003",
        comment:"sdgvedrgverdgvswe dv dvc dsv sdvc sdv sdxvc vdsvdsv edvc x",
        category: "commity",
        organizer: "Secretory",
        important: true, 
        content:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",       
    },
    {
        id: 13,
        title: "the event",
        image:  "https://images.unsplash.com/photo-1682252913872-2ec60d4b0818?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=876&q=80"  ,
        date: "10/3/2003",
        comment:"sdgvedrgverdgvswe dv dvc dsv sdvc sdv sdxvc vdsvdsv edvc x",
        category: "commity",
        organizer: "Secretory",
        important: true,   
        content:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",     
    },
    {
        id: 14,
        title: "the event",
        image:  "https://images.unsplash.com/photo-1682252913872-2ec60d4b0818?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=876&q=80"  ,
        date: "10/3/2003",
        comment:"sdgvedrgverdgvswe dv dvc dsv sdvc sdv sdxvc vdsvdsv edvc x",
        category: "commity",
        organizer: "Secretory",
        important: true,   
        content:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",     
    },
    {
        id: 1,
        title: "the edfdsvent",
        image:  "https://media.geeksforgeeks.org/img-practice/banner/cp-maths-java-thumbnail.png" ,
        date: "10/3/2003",
        comment:"sdgvedrgverdgvswe dv dvc dsv sdvc sdv sdxvc vdsvdsv edvc x",
        category: "society",
        organizer: "Commitee",
        important: false,
        content:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.", 
    },
    {
        id: 2,
        title: "the evengsgst",
        image:  "https://images.unsplash.com/photo-1682252913872-2ec60d4b0818?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=876&q=80"  ,
        date: "10/3/2003",
        comment:"sdgvedrgverdgvswe dv dvc dsv sdvc sdv sdxvc vdsvdsv edvc x",
        category: "gym",
        organizer: "Gym head",
        important: false, 
        content:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    },
    {
        id: 3,
        title: "the evedsfdnt",
        image:  "https://media.geeksforgeeks.org/img-practice/banner/cp-maths-java-thumbnail.png"  ,
        date: "10/3/2003",
        comment:"sdgvedrgverdgvswe dv dvc dsv sdvc sdv sdxvc vdsvdsv edvc x",
        category: "society",
        organizer: "commitee",
        important: true, 
        content:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    },
    {
        id: 15,
        title: "the evedsfdnt",
        image:  "https://media.geeksforgeeks.org/img-practice/banner/cp-maths-java-thumbnail.png"  ,
        date: "10/3/2003",
        comment:"sdgvedrgverdgvswe dv dvc dsv sdvc sdv sdxvc vdsvdsv edvc x",
        category: "society",
        organizer: "commitee",
        important: true, 
        content:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    },
    {
        id: 16,
        title: "the evedsfdnt",
        image:  "https://media.geeksforgeeks.org/img-practice/banner/cp-maths-java-thumbnail.png"  ,
        date: "10/3/2003",
        comment:"sdgvedrgverdgvswe dv dvc dsv sdvc sdv sdxvc vdsvdsv edvc x",
        category: "society",
        organizer: "commitee",
        important: true, 
        content:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    },
    {
        id: 17,
        title: "the evedsfdnt",
        image:  "https://media.geeksforgeeks.org/img-practice/banner/cp-maths-java-thumbnail.png"  ,
        date: "10/3/2003",
        comment:"sdgvedrgverdgvswe dv dvc dsv sdvc sdv sdxvc vdsvdsv edvc x",
        category: "society",
        organizer: "commitee",
        important: true, 
        content:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    },
    {
        id: 4,
        title: "the esfzdvent",
        image:  "https://media.geeksforgeeks.org/img-practice/banner/cp-maths-java-thumbnail.png"  ,
        date: "10/3/2003",
        comment:"sdgvedrgverdgvswe dv dvc dsv sdvc sdv sdxvc vdsvdsv edvc x",
        category: "cultural",
        organizer: "cutural Secretory",
        important: false,
        content:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.", 
    },
    {
        id: 18,
        title: "the esfzdvent",
        image:  "https://media.geeksforgeeks.org/img-practice/banner/cp-maths-java-thumbnail.png"  ,
        date: "10/3/2003",
        comment:"sdgvedrgverdgvswe dv dvc dsv sdvc sdv sdxvc vdsvdsv edvc x",
        category: "cultural",
        organizer: "cutural  Secretory",
        important: false, 
        content:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    },
    {
        id: 19,
        title: "the esfzdvent",
        image:  "https://media.geeksforgeeks.org/img-practice/banner/cp-maths-java-thumbnail.png"  ,
        date: "10/3/2003",
        comment:"sdgvedrgverdgvswe dv dvc dsv sdvc sdv sdxvc vdsvdsv edvc x",
        category: "cultural",
        organizer: "cutural Secretory",
        important: false, 
        content:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    },
    {
        id: 20,
        title: "the esfzdvent",
        image:  "https://media.geeksforgeeks.org/img-practice/banner/cp-maths-java-thumbnail.png"  ,
        date: "10/3/2003",
        comment:"sdgvedrgverdgvswe dv dvc dsv sdvc sdv sdxvc vdsvdsv edvc x",
        category: "cultural",
        organizer: "cutural Secretory",
        important: false, 
        content:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    },
    {
        id: 5,
        title: "the dsfevent",
        image:  "https://images.unsplash.com/photo-1682252913872-2ec60d4b0818?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=876&q=80"  ,
        date: "10/3/2003",
        comment:"sdgvedrgverdgvswe dv dvc dsv sdvc sdv sdxvc vdsvdsv edvc x",
        category: "commity",
        organizer: "cutural Secretory",
        important: true, 
        content:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    },
    {
        id: 6,
        title: "the event",
        image:  "https://media.geeksforgeeks.org/img-practice/banner/diving-into-excel-thumbnail.png"  ,
        date: "10/3/2003",
        comment:"sdgvedrgverdgvswe dv dvc dsv sdvc sdv sdxvc vdsvdsv edvc x",
        category: "commity",
        organizer: "cutural Secretory",
        important: false,
        content:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.", 
    },
    {
        id: 7,
        title: "the edfdsvent",
        image:  "https://images.unsplash.com/photo-1682252913872-2ec60d4b0818?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=876&q=80"  ,
        date: "10/3/2003",
        comment:"sdgvedrgverdgvswe dv dvc dsv sdvc sdv sdxvc vdsvdsv edvc x",
        category: "society",
        organizer: "Commitee",
        important: true, 
        content:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    },
    {
        id: 8,
        title: "the evengsgst",
        image:  "https://images.unsplash.com/photo-1682252913872-2ec60d4b0818?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=876&q=80"  ,
        date: "10/3/2003",
        comment:"sdgvedrgverdgvswe dv dvc dsv sdvc sdv sdxvc vdsvdsv edvc x",
        category: "gym",
        organizer: "Gym head",
        important: false,
        content:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.", 
    },
    {
        id: 9,
        title: "the evedsfdnt",
        image:  "https://media.geeksforgeeks.org/img-practice/banner/cp-maths-java-thumbnail.png"  ,
        date: "10/3/2003",
        comment:"sdgvedrgverdgvswe dv dvc dsv sdvc sdv sdxvc vdsvdsv edvc x",
        category: "society",
        organizer: "Commitee",
        important: true, 
        content:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    },
    {
        id: 10,
        title: "the esfzdvent",
        image:  "https://media.geeksforgeeks.org/img-practice/banner/diving-into-excel-thumbnail.png"  ,
        date: "10/3/2003",
        comment:"sdgvedrgverdgvswe dv dvc dsv sdvc sdv sdxvc vdsvdsv edvc x",
        category: "cultural",
        organizer: "cutural Secretory",
        important: true, 
        content:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    },
    {
        id: 21,
        title: "the esfzdvent",
        image:  "https://media.geeksforgeeks.org/img-practice/banner/diving-into-excel-thumbnail.png"  ,
        date: "10/3/2003",
        comment:"sdgvedrgverdgvswe dv dvc dsv sdvc sdv sdxvc vdsvdsv edvc x",
        category: "cultural",
        organizer: "cutural Secretory",
        important: true, 
        content:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    },
    {
        id: 11,
        title: "the dsfevent",
        image:  "https://media.geeksforgeeks.org/img-practice/banner/cp-maths-java-thumbnail.png"  ,
        date: "10/3/2003",
        comment:"sdgvedrgverdgvswe dv dvc dsv sdvc sdv sdxvc vdsvdsv edvc x",
        category: "commity",
        organizer: "Secretory",
        important: false, 
        content:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    }
];
export default event_doc;